spring:
  application:
    name: Spring-keycloak
    version: 1.0.0


  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update  # Mettez à jour la base de données à chaque démarrage (vous pouvez le changer à 'none' ou 'create' selon votre besoin)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}

server:
  port: ${APP_PORT}  # Port exposé pour l'application Spring Boot

application:
  keycloak:
    baseurl: ${KEYCLOAK_BASE_URL}
    client-id: ${KEYCLOAK_CLIENT_ID}
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
    realm: ${KEYCLOAK_REALM}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
logging:
  file:
    path: /var/log/spring-boot/
