spring:
  application:
    name: Spring-keycloak
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://localhost:5435/app_db
    username: admin
    password: admin@123
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: 8001

